<?php

function template_forgot_password ($data=null) {
    $htmlBody = '<figure class="table">
    <table style="background-color:rgb(234, 234, 234);background-image:url("https://ci3.googleusercontent.com/meips/ADKq_NY1kR9QuSQ0p3XO37t82mhxLwX4B629aBl6jISsS-yhiRf7994ZWNgmHZpxYqeYcfA-Qn8BxQDYD8VoW6xOwEGVAEei-3Uw8l64d3XoHTNyvIY=s0-d-e1-ft#https://www.twilio.com/resources/images/email/background.jpg");border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:Whitney-SSm-A, Whitney-SSm-B, Whitney, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:13px;margin:0px;min-width:750px;padding:0px;text-align:center;vertical-align:baseline;">
        <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
            <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:top;">
                    <figure class="table" style="width:680px;">
                        <table style="background-color:rgb(255, 255, 255);border-collapse:collapse;border-spacing:0px;border:1px solid rgb(221, 221, 221);box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px auto;max-width:680px;padding:0px;vertical-align:baseline;">
                            <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                    <td style="border-bottom:1px solid rgb(221, 221, 221);border-image:initial;border-left-color:initial;border-left-width:0px;border-right-color:initial;border-right-width:0px;border-top-color:initial;border-top-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                        <div style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:20px;padding:0px;vertical-align:baseline;"><img class="CToWUd" style="border-style:none;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;outline:none;padding:0px;vertical-align:baseline;" src="https://res.cloudinary.com/dqfi9qukb/image/upload/v1720461079/dsyl3l2mmfhgssfercsu.png" alt="DIGIPAYID" width="150" height="150" data-bit="iit" jslog="138226; u014N:xr6bB; 53:WzAsMl0."></div>
                                    </td>
                                </tr>
                                <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                    <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                        <figure class="table" style="width:unset;">
                                            <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;display:inline-block;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:10px 20px;vertical-align:baseline;">
                                                <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                    <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                        <td style="border-bottom:1px solid rgb(221, 221, 221);border-image:initial;border-left-color:initial;border-left-width:0px;border-right-color:initial;border-right-width:0px;border-top-color:initial;border-top-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                                            <figure class="table" style="width:558px;">
                                                                <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;max-width:558px;padding:0px;vertical-align:baseline;">
                                                                    <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:60px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:20px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><strong>DIGIPAYID Change Password</strong></p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;">You need to click this link for changing your DIGIPAYID Password.</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:60px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:20px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><a href="'.getenv('FE_DOMAIN_BASE_URL').'auth/new-password?token='.$data.'"><strong>Click here to Change Password.</strong></a></p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </figure>
                                                        </td>
                                                    </tr>
                                                    <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                        <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                                            <figure class="table" style="width:558px;">
                                                                <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;max-width:558px;padding:0px;vertical-align:baseline;">
                                                                    <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><i>The request for this access originated from DIGIPAYID App</i></p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;">In case you were not trying to access your DIGIPAYID Account &amp; are seeing this email, please follow the instructions below:</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:10px;line-height:inherit;margin:0px;padding:0px 0px 0px 20px;vertical-align:middle;" align="left">
                                                                                <ul style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;list-style-image:initial;list-style-position:initial;margin-bottom:0px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;"><span class="il">Reset</span>&nbsp;your DIGIPAYID <span class="il">password</span>.</p>
                                                                                    </li>
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;">Check if any&nbsp; <span class="il">changes</span>&nbsp;were made to your account &amp; user settings. If yes, revert them immediately.</p>
                                                                                    </li>
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;">If you are unable to access your DIGIPAYID &nbsp;Account then contact DIGIPAYID Support.</p>
                                                                                    </li>
                                                                                </ul>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </figure>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </figure>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </figure>
                    <p>&nbsp;</p>
                    <p>DIGIPAYID&nbsp;</p>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
    ';

    return $htmlBody;
}

function template_email_otp ($data=null) {
    $htmlBody = '
    <figure class="table">
    <table style="background-color:rgb(234, 234, 234);background-image:url(;" https:="" ci3.googleusercontent.com="" meips="" adkq_ny1kr9qusq0p3xo37t82mhxlwx4b629abl6jisss-yhirf7994zwngmhzpxyqeycfa-qn8bxqdyd8vow6xowegvaeei-3uw8l64d3xohtnyviy="s0-d-e1-ft#https://www.twilio.com/resources/images/email/background.jpg&quot;);border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:Whitney-SSm-A,">
        <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
            <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:top;">
                    <figure class="table" style="width:680px;">
                        <table style="background-color:rgb(255, 255, 255);border-collapse:collapse;border-spacing:0px;border:1px solid rgb(221, 221, 221);box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px auto;max-width:680px;padding:0px;vertical-align:baseline;">
                            <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                    <td style="border-bottom:1px solid rgb(221, 221, 221);border-image:initial;border-left-color:initial;border-left-width:0px;border-right-color:initial;border-right-width:0px;border-top-color:initial;border-top-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                        <div style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:20px;padding:0px;vertical-align:baseline;"><img class="CToWUd" style="border-style:none;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;outline:none;padding:0px;vertical-align:baseline;" src="https://res.cloudinary.com/dqfi9qukb/image/upload/v1720461079/dsyl3l2mmfhgssfercsu.png" alt="DIGIPAYID" width="150" height="150" data-bit="iit" jslog="138226; u014N:xr6bB; 53:WzAsMl0."></div>
                                    </td>
                                </tr>
                                <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                    <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                        <figure class="table" style="width:unset;">
                                            <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;display:inline-block;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:10px 20px;vertical-align:baseline;">
                                                <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                    <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                        <td style="border-bottom:1px solid rgb(221, 221, 221);border-image:initial;border-left-color:initial;border-left-width:0px;border-right-color:initial;border-right-width:0px;border-top-color:initial;border-top-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                                            <figure class="table" style="width:558px;">
                                                                <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;max-width:558px;padding:0px;vertical-align:baseline;">
                                                                    <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:60px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:20px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><strong>DIGIPAYID OTP</strong></p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;">Your OTP DIGIPAYID is : </p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:60px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:20px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><strong>'.$data.'</strong></p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </figure>
                                                        </td>
                                                    </tr>
                                                    <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                        <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;">
                                                            <figure class="table" style="width:558px;">
                                                                <table style="border-collapse:collapse;border-spacing:0px;border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;max-width:558px;padding:0px;vertical-align:baseline;">
                                                                    <tbody style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;"><i>The request for this access originated from DIGIPAYID App</i></p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:50px;line-height:inherit;margin:0px;padding:0px;vertical-align:middle;" align="left">
                                                                                <p style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin:0px;padding:0px;vertical-align:baseline;">In case you were not trying to access your DIGIPAYID Account &amp; are seeing this email, please follow the instructions below:</p>
                                                                            </td>
                                                                        </tr>
                                                                        <tr style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">
                                                                            <td style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;height:10px;line-height:inherit;margin:0px;padding:0px 0px 0px 20px;vertical-align:middle;" align="left">
                                                                                <ul style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;font-weight:inherit;line-height:inherit;list-style-image:initial;list-style-position:initial;margin-bottom:0px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;"><span class="il">Reset</span>&nbsp;your DIGIPAYID <span class="il">password</span>.</p>
                                                                                    </li>
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;">Check if any&nbsp; <span class="il">changes</span>&nbsp;were made to your account &amp; user settings. If yes, revert them immediately.</p>
                                                                                    </li>
                                                                                    <li style="border-width:0px;box-sizing:inherit;font-family:inherit;font-feature-settings:inherit;font-kerning:inherit;font-optical-sizing:inherit;font-size:14px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-variation-settings:inherit;line-height:20px;margin-bottom:5px;margin-right:0px;margin-top:0px;padding:0px;vertical-align:baseline;">
                                                                                        <p style="margin-left:0px;">If you are unable to access your DIGIPAYID &nbsp;Account then contact DIGIPAYID Support.</p>
                                                                                    </li>
                                                                                </ul>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </figure>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </figure>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </figure>
                    <p>&nbsp;</p>
                    <p>DIGIPAYID&nbsp;</p>
                </td>
            </tr>
        </tbody>
    </table>
</figure>
    ';

    return $htmlBody;
}